package input

import (
	vpad "github.com/kemokemo/ebiten-virtualpad"
)

type TitleInputChecker struct {
	StartBtn vpad.TriggerButton
}

// memo:
// These implementations are generated by below.
// impl 'i *TitleInputChecker' InputChecker >> title-input.go

func (i *TitleInputChecker) Update() {
	i.StartBtn.Update()
}

func (i *TitleInputChecker) TriggeredUp() bool {
	return false
}

func (i *TitleInputChecker) TriggeredDown() bool {
	return false
}

func (i *TitleInputChecker) TriggeredLeft() bool {
	return false
}

func (i *TitleInputChecker) TriggeredRight() bool {
	return false
}

func (i *TitleInputChecker) TriggeredStart() bool {
	return i.StartBtn.IsTriggered()
}

func (i *TitleInputChecker) TriggeredPause() bool {
	return false
}

func (i *TitleInputChecker) TriggeredAttack() bool {
	return false
}

func (i *TitleInputChecker) TriggeredSkill() bool {
	return false
}
