name: Deploy GitHub pages

on:
  push:
    branches:
      - main
    paths:
      - 'internal/**'
      - 'assets/**'
      - 'public/**'

jobs:
  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.4'

      - name: Build WebAssembly
        run: |
          GOOS=js GOARCH=wasm go build -ldflags="-X 'main.Revision=$(git rev-parse --short HEAD)'" -o ./public/kuronan-dash.wasm

      - name: Copy wasm exec
        run: cp $(go env GOROOT)/lib/wasm/wasm_exec.js ./public/js

      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './public'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
